### ISSUE TITLE
How to throw Exception to Client When HTTP 404

### ISSUE THREAD

**Issue by thusithathilina** [coveo/feign-error-decoder#1]
Thanks for sharing this. I tried this with for exception which is thrown with the HTTP 404.  In that case, I'm not getting the intended exception to the client.
I checked the code and https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Util.java#L233 always returns null when the status code is 404. Then it will not go to the if condition in https://github.com/coveo/feign-error-decoder/blob/master/src/main/java/com/coveo/feign/ReflectionErrorDecoder.java#L82 and always go to fallbackErrorDecoder.
How can I get the exception to the client with HTTP status code 404

**Comment by jebeaudet** [comment]
I find it odd that Feign return empties/null on 404 response as they can have bodies like any other status code. 404 can mean that the passed parameters to the api are not found, it's not only used in the case of a wrong path...

Anyway, you have 3 choices here I believe : 
- Override the implementation of `Decoder` (`JacksonDecoder`, `GsonDecoder`, etc.) to change the behaviour on 404 responses.
- Override `ReflectionErrorDecoder` to add specific handling for 404 responses.
- Use a fallback `ErrorDecoder` that has a code path for 404 responses.

Does this help you?

**Comment by thusithathilina** [comment]
@jebeaudet Thanks for the detailed explanation and solutions. Will try them out. Do you think that this should be requested as an improvement from Fegin client?

**Comment by jebeaudet** [comment]
I think it could, having the body of the request decoded in the case of a 404
is a genuine use case IMO.

**Comment by thusithathilina** [comment]
I've raised that to Fegin client :) https://github.com/OpenFeign/feign/issues/476 Thanks for the support. I'll close this now.

**Comment by hellboy81** [comment]
https://github.com/coveo/feign-error-decoder/issues/1#issuecomment-252943713

@thusithathilina @jebeaudet what is the best choice to map "404" error responses to own Exception classes?

**Comment by jebeaudet** [comment]
@hellboy81 You mean in the three bullets points I listed? I would go for the first one.

**Comment by hellboy81** [comment]
I have  chosen
```
* Use a fallback `ErrorDecoder` that has a code path for 404 responses.
````
and it works for me

- which disadvantages has this solution? 
- can you provide link to sample code implemented "the first one silver bullet" ?

**Comment by jebeaudet** [comment]
I think the option of the `Decoder` is cleaner since you don't modify the normal flow of the request. Not decoding 404 is non sense IMO so modify that by injecting your own `Decoder` makes total sense and does not create a new code path for 404 responses.

I don't have a sample, just inject your own implementation that decodes 404 responses in the `Feign.Builder` you're probably using to build your client. Check the source code of the existing implementations (ie. `JacksonDecoder`) for inspiration of simply extend it.
