### ISSUE TITLE
Question on key selection

### ISSUE THREAD

**Issue by silentFred** [coveo/feign-error-decoder#4]
Hi there,

Firstly thanks for sharing this in a lib. A much better approach than the one i was trying :P

I'm not entirely clear on the implementation bit of the decoder. We have about 5 fields that come back from an error in our ecosystem. (Application name, span id, trace id, http code, message) and I'm not too sure how to map them given the abstract methods i should implement?

**Comment by jebeaudet** [comment]
Hi!

To uniquely associate an error received from a server to a typed exception, you need a key for the mapping. In this library, we assume that the key is provided by a `String`. Though from what I can see with what you provided, you don't seem to have something to map from the response to the typed exception (unless `message` is unique and static for each exception then you could use that). I've explained it a bit further here, hopefully it'll help you.

Let's say on the server side you have an exception that extends your [base exception class](https://github.com/coveo/feign-error-decoder#base-exception-class) like this : 
```java
public class SomethingWentWrongException extends ServiceException {
  private static final String ERROR_CODE = "SOMETHING_WENT_WRONG";
  
  public SomethingWentWrongException() {
    super(ERROR_CODE);
  }
}
```
This exception gets thrown and handled in your code in the [typed error object](https://github.com/coveo/feign-error-decoder#class-for-the-error-response) into this body (JSON is used here but it could be XML with the proper decoder) : 
```json
{
  "errorCode" : "SOMETHING_WENT_WRONG",
  "message" : "You screwed up"
}
```
On the client side, you would have an API like this : 
```java
public interface UserApi {
    @RequestMapping("/user/{username}")
    User getUser(@PathVariable String username) throws SomethingWentWrongException;
}
```
You then create your Feign client with an instance of the `ReflectionErrorDecoder` pointing on this interface. The instance will deserialize this body into a `ErrorCodeAndMessage`. From there, it uses the abstract methods to find the key (`SOMETHING_WENT_WRONG` in this example) and the message to reconstruct an instance of `SomethingWentWrongException`.

You also have a code example in the [test package](https://github.com/coveo/feign-error-decoder/blob/master/src/test/java/com/coveo/feign/ServiceExceptionErrorDecoder.java).

**Comment by jebeaudet** [comment]
Yes exactly, the exceptions need to be shared among the projects and extends the same base exception. 

Thanks for the kind words, I'll close this one and don't hesitate to open another issue if you run into an issue.
