### ISSUE TITLE
[Question] [support needed] Error Response Body is empty

### ISSUE THREAD

**Issue by hellboy81** [coveo/feign-error-decoder#6]
I am trying to decode error response body but got always `null`:

code specific `ErrorCodes`  error Exception classes are generated properly but with empty body:

![image](https://user-images.githubusercontent.com/341600/59361426-1f07d900-8d32-11e9-88fb-364f9999e6a4.png)

`Feign`'s `OkHttp` client is used.

Where is my bad?

P.S. Another developers from UA reported `feign-error-decoder` does not work properly.

See also my question in chat.

**Comment by jebeaudet** [comment]
Which version of Feign are you using?

Also, I'm not sure I understand your question, are you saying the exception is being rethrown properly but with `null` as the `ErrorResponse` parameter? Did you override the supported constructors arguments [as mentioned here](https://github.com/coveo/feign-error-decoder#supported-constructor-arguments) to make that work?

If that's the case, this won't work as the library was not designed to work like this.

**Comment by hellboy81** [comment]
sorry wrong github repo:

See: [feign-annotation-error-decoder from OpenFeign repo](https://github.com/OpenFeign/feign-annotation-error-decoder/issues/24)
